project:
  type: website

website:
  title: "Joshua Lim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd  
        text: Experience

  page-footer:
    right: "&copy; 2024, Joshua Lim"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



execute:
  freeze: auto

